name: CastleRaidCore
version: 1.4.3
author: QuiverlyRivalry, iiFlamiinBlaze
api: [3.0.0-ALPHA9, 3.0.0-ALPHA10]
main: CRCore\Loader
depend:
- FormAPI
permissions:
 castleraid.nick:
  default: true
 cp.command:
  default: true
 mp.command:
  default: true
 cp2.command:
  default: true
 castleraid.info:
  default: true
 castleraid.heal:
  default: op
 castleraid.fly:
  default: op
 castleraid.clearinv:
  default: op
